version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  omnidb:
    image: omnidbteam/omnidb
    privileged: true
    user: root
    volumes:
      - my_volume:/home/omnidb/.omnidb/omnidb-server
    links:
      - postgres:postgres
    ports:
      - '${OMNI_DB_PORT}:8000'
      - '25482:25482'

volumes:
  my_volume:
